# Generated by Django 3.1.3 on 2020-11-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vessels.vessel')),
            ],
        ),
    ]
