# Generated by Django 3.1.3 on 2020-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20201115_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='code',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
