# Generated by Django 3.1.3 on 2020-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20201116_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='id',
        ),
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default=12, max_length=150),
            preserve_default=False,
        ),
    ]
