# Generated by Django 3.1.3 on 2020-11-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
